version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/data.json:/app/data.json
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
